- name: Load Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install mysql client server
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load schema
  ansible.builtin.shell: mysql -h mysql.vdevops21.online -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load user creation
  ansible.builtin.shell: mysql -h mysql.vdevops21.online -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load Master Data
  ansible.builtin.shell: mysql -h mysql.vdevops21.online -uroot -pRoboShop@1 < /app/db/master-data.sql

